{#
 # @author wesen
 # @copyright 2020 wesen <wesen-ac@web.de>
 # @release 0.1
 # @license MIT
 #}

<!doctype html>
<html lang="en">
  <head>
    <title>Code coverage report for {{ reportTarget }}</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{* relativePathToRoot .. "style/reset.css" *}">
    <link rel="stylesheet" href="{* relativePathToRoot .. "style/style.css" *}">
  </head>
  <body>
   <div id="page-container">
      <header>
        <nav>
          {[ templateDirectoryPath .. "/fragments/navigatablepath.tpl" ]}
        </nav>
      </header>

      <main>
        <header class="hit-miss-statistics">
          {[ templateDirectoryPath .. "/fragments/hitmissstatistics.tpl" ]}
        </header>
        <section id="content">
          {* blocks.content *}
        </section>
      </main>

      <footer class="quiet">
        Code coverage generated by <a href="https://keplerproject.github.io/luacov/" target="_blank">LuaCov</a> at {{ startTimestamp }}
      </footer>
    </div>
  </body>
</html>
